### ISSUE TITLE
Stuck at retrieving info screen

### ISSUE THREAD

**Issue by AndhikaWB** [Ochii/cso2-master-services#14]
**Some info about installed program**
1) MongoDB Community x64 (complete install) v4.0.10
2) Node.js x64 (LTS release) v10.16.0
3) I don't have git/curl/tar installed as I downloaded the whole "master services" (inventory, master, users, webapp) from Chrome, I also already run npm install (development) on each service/server folder

**Step to reproduce**
1) Run "start_services.ps1" file and wait for a while
2) PowerShell window shows up with 0 and 1 number, and then close/hide itself (I didn't do anything)
3) 4 command prompt windows appear
4) Start the game by running the "start-cso2.bat" file (with master server = my local IP)
5) Black screen for about 15 seconds and login screen appear
6) Login using "Andhika" as username and "123" as password
7) The game stuck at "Retrieving version info" for long time

**Screenshot/logs**
1) users-service "combined.log" file ([here](https://pastebin.com/untawCuh))
2) Some screenshot ([pic 1](http://prnt.sc/obcaxf), [pic 2](https://prnt.sc/obcb8w), [pic 3](https://prnt.sc/obcbfa))

**My system info**
1) Windows 10 x64 (LTSC release)
2) 12 GB of RAM - I don't think this is important tho

**Comment by DebugBios** [comment]
You have to create an account.

If you connect to the server ip:8080, you will be able to sign up for membership.

**Comment by AndhikaWB** [comment]
Thanks, I tried that but there's no such host.

**Comment by DebugBios** [comment]
If it doesn't work, I think it'd be better to reinstall

https://git-scm.com/downloads after installing


Run PowerShell as administrator. 

Enter set-executionpolicy bypass, allow script 

In the PowerShell, type:

cd C:\Users\(windowusername)\Desktop
git close https://github.com/Ochii/cso2-master-services master-services
cd master-services
git submodule update --init
.\setup_services.ps1

This installs it, but because of an error, the web app is not installed and may need to be installed manually.

**Comment by AndhikaWB** [comment]
I fixed it by redownloading "webapp" repo, it seems that "src" folder was missing on my case for a strange reason. I can now register and play the game. Thanks. By the way I don't "setup_services.ps1", I run "npm install" manually on each folder.
